version: '3.2'
services:
    DiskSyncPostgres:
       build:
            context: ./postgres
       image: postgres
       ports:
        - "5432:5432"
       container_name: DiskSyncPostgres
       environment:
        - POSTGRES_DB=DiskSyncDataBase
        - POSTGRES_USER=SuperUser
        - POSTGRES_PASSWORD=1234










